
NUM_GPUS: [0, 1]

TRAIN:
  RESUME: false
  RESUMEPATH: ''
  EPISODES: 10000000
  BATCHSIZE: 64
  TRAINSTART: 50000
  LR: 0.0000625
  EPSILON: 1.0
  EPSILONMIN: 0.001
  EPSILONDECAY: 1000000
  EPSILONSTEP: [0.1, 0.05]
  EPSILONSTEPDECAY: 10
  DISCOUNTFACTOR: 0.99
  ALPHA: 0.6
  BETA: 0.4
  BETAMAX: 1.0
  BETADECAY: 3000000
  BUFFERSIZE: 1000000

DEMO:
  MODELPATH: ''

CELLSIZE: 30
COLUMNS: 7
ROWS: 14
MAXFPS: 30
BOUNDARYSIZE: 7
GAMESCORE: 0

COLORS: [
  [0, 0, 0],
  [255, 85, 85],
  [100, 200, 115],
  [120, 108, 245],
  [255, 140, 50],
  [50, 120, 52],
  [146, 202, 73],
  [150, 161, 218],
  [35, 35, 35]
]

TETRISSHAPES: [
[[1, 1, 1, 1]],

[[2, 0],
 [2, 2],
 [2, 0]],

[[3, 3],
 [3, 3]],

[[4, 0],
 [4, 4],
 [0, 4]],

[[5, 0],
 [5, 0],
 [5, 5]],

[[0, 6],
 [6, 6],
 [6, 0]],

[[0, 7],
 [0, 7],
 [7, 7]]
]