
CUDA_VISIBLE_DEVICES: '0'

MODE: 'train'

TRAIN:
  RESUME: false
  RESUMEPATH: ''

TEST:
  MODELPATH: ''

CELLSIZE: 30
COLUMNS: 7
ROWS: 14
MAXFPS: 30
BOUNDARYSIZE: 7
GAMESCORE: 0

COLORS: [
  [0, 0, 0],
  [255, 85, 85],
  [100, 200, 115],
  [120, 108, 245],
  [255, 140, 50],
  [50, 120, 52],
  [146, 202, 73],
  [150, 161, 218],
  [35, 35, 35]  # Helper color for background grid
]

TETRISSHAPES: [

[[1, 1, 1, 1]],

[[2, 0],
 [2, 2],
 [2, 0]],

[[3, 3],
 [3, 3]],

[[4, 0],
 [4, 4],
 [0, 4]],

[[5, 0],
 [5, 0],
 [5, 5]],

[[0, 6],
 [6, 6],
 [6, 0]],

[[0, 7],
 [0, 7],
 [7, 7]]
]